console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#000000'
  blue = '#AA96A5'
  green = '#E8CC73'
  orange = '#D9B18E'
  red = '#CE9D73'
  white = '#d8cfdd'
  yellow = '#7F728F'

[transient_prompt]
  template = '> '
  foreground = 'red'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'black'
    background = 'blue'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ path .Path .Location }} '
    foreground = 'black'
    powerline_symbol = ''
    background = 'red'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'black'
    powerline_symbol = ''
    background = 'cyan'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:black{{ end }}', '{{ if gt .Ahead 0 }}p:black{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = ' {{ if eq .Code 0 }} {{else}} ⓧ Error {{ end }} '
    foreground = '#ff0000'
    type = 'status'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  '
    foreground = '#d8cfdd'
    background = '#000000'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = '  '
    foreground = '#d8cfdd'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ if .Venv }}({{ .Venv }}){{ end }} '
    foreground = 'black'
    powerline_symbol = ''
    background = 'blue'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'environment'
      fetch_virtual_env = true
      home_enabled = true
